#!/usr/bin/env bash
#shellcheck disable=SC2154
#install nginX and configure-a custom http header

sudo apt-get -y update
sudo apt-get -y install nginx

#a firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

#set permission to create files in this repo
sudo chmod -R 755 /var/www

#set index page
echo 'Hello World!' |sudo tee /var/wwww/html/index.html

#create 404 error page
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# Set redirect for a single page  and add header to show hostname (/redirect_me)
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.ella7d.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Set redirect for error 404 page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#restart web server
sudo service nginx restart
