#!/usr/bin/env bash
# Install haproxy and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

#HAproxy configuration
cat << EOF > /etc/haproxy/haproxy.cfg

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 105716-web-01 18.204.9.63:80 check
	server 105716-web-02 54.237.101.234:80 check
EOF
#hostname configuration update
echo "18.204.9.63"> /etc/hostname
echo "54.237.101.234">> /etc/hostname

#To enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#Start HAproxy
/etc/init.d/haproxy start
