#!/usr/bin/env bash
# Install haproxy and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

#HAproxy configuration
cat << EOF > /etc/haproxy/haproxy.cfg

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 105716-web-01 54.175.32.23:80 check
	server 105716-web-02 18.206.198.73:80 check
EOF
#hostname configuration update
echo "54.175.32.23"> /etc/hostname
echo "18.206.198.73">> /etc/hostname

#To enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#Start HAproxy
/etc/init.d/haproxy start
