#!/usr/bin/env bash
#to make nginx inactive or kills the end process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -SIGKILL -f "/usr/sbin/nginx"
